# Generated by Django 4.1.7 on 2023-03-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
